// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw8Lum6nlcEkRaQn-kEKNcnnjlCarQF6k',
    appId: '1:468385627622:web:c8b3a04c2e4ed286d0aa27',
    messagingSenderId: '468385627622',
    projectId: 'chatapp-d15f0',
    authDomain: 'chatapp-d15f0.firebaseapp.com',
    databaseURL: 'https://chatapp-d15f0-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-d15f0.appspot.com',
    measurementId: 'G-FXT6FZYJ95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaYusAKmeJohvJQoKLf2Qw9G4eoCWK5Y',
    appId: '1:468385627622:android:03918c9ed7fc9673d0aa27',
    messagingSenderId: '468385627622',
    projectId: 'chatapp-d15f0',
    databaseURL: 'https://chatapp-d15f0-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-d15f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVxFz9adOnDscbxRKTt8qM4YQTTwe1V8',
    appId: '1:468385627622:ios:5eda3f17f617f1b0d0aa27',
    messagingSenderId: '468385627622',
    projectId: 'chatapp-d15f0',
    databaseURL: 'https://chatapp-d15f0-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-d15f0.appspot.com',
    iosClientId: '468385627622-73k0ed88do4di3et9ekpv0fbj6d0neu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.restoAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVxFz9adOnDscbxRKTt8qM4YQTTwe1V8',
    appId: '1:468385627622:ios:07cadcb06ed24a55d0aa27',
    messagingSenderId: '468385627622',
    projectId: 'chatapp-d15f0',
    databaseURL: 'https://chatapp-d15f0-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-d15f0.appspot.com',
    iosClientId: '468385627622-l2l3oqabjp5oosced49nln18mprccfoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.restoAdmin.RunnerTests',
  );
}
